[package]
name = "yake-rust"
version = "0.1.8"
edition = "2021"
authors = ["Kyle Fahey <kyle.c.r.fahey@gmail.com>"]
keywords = ["keyword", "nlp", "keywords", "extractor"]
repository = "https://github.com/quesurifn/yake-rust"
description = "Yake (Yet Another Keyword Extractor) in Rust"
readme = "README.md"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
streaming-stats = "0.1.28"
contractions = "0.5.4"
unicode-segmentation = "1.9.0"
natural = "0.3.0"

[lib]
path = "src/lib.rs"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
